### ISSUE TITLE
undefined method `blank?' for String

### ISSUE THREAD

**Issue by aashay** [yatish27/salesforce_bulk_api#30]
https://github.com/yatish27/salesforce_bulk_api/blob/master/lib/salesforce_bulk_api/connection.rb#L78

AFAIK "blank?" is an ActiveSupport thing, which doesn't seem to be a dependency of this gem at all.  Attempting to authenticate with the SFDC API returns the following trace:

```
/Users/aashay/dev/labs/salesforce/ruby/vendor/bundle/gems/salesforce_bulk_api-0.0.9/lib/salesforce_bulk_api/connection.rb:78:in `parse_instance': undefined method `blank?' for "cs10":String (NoMethodError)
	from /Users/aashay/dev/labs/salesforce/ruby/vendor/bundle/gems/salesforce_bulk_api-0.0.9/lib/salesforce_bulk_api/connection.rb:35:in `login'
	from /Users/aashay/dev/labs/salesforce/ruby/vendor/bundle/gems/salesforce_bulk_api-0.0.9/lib/salesforce_bulk_api/connection.rb:20:in `initialize'
	from /Users/aashay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/salesforce_bulk_api-0.0.9/lib/salesforce_bulk_api.rb:18:in `new'
	from /Users/aashay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/salesforce_bulk_api-0.0.9/lib/salesforce_bulk_api.rb:18:in `initialize'
	from ./bulk.rb:19:in `new'
	from ./bulk.rb:19:in `<main>'
```

**Comment by gostrc** [comment]
Just encountered this also in 0.0.10.

The fix would be to either use something other than .blank? which accomplishes the same thing, or just add activesupport as a dependency to the gemspec.
