### ISSUE TITLE
Occasionally getting "undefined method `[]' for nil:NilClass" errors in salesforce_bulk_api gem

### ISSUE THREAD

**Issue by thomasdziedzic** [yatish27/salesforce_bulk_api#54]
I suspect that this is due to salesforce sending a response that this gem doesn't expect.

```
/u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/activerecord-3.2.17/lib/active_record/associations/has_many_association.rb:80: warning: circular argument reference - reflection
/u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/railties-3.2.17/lib/rails/commands/runner.rb:54:in `eval': undefined method `[]' for nil:NilClass (NoMethodError)
        from /u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/salesforce_bulk_api-0.0.12/lib/salesforce_bulk_api/job.rb:175:in `each'
        from /u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/salesforce_bulk_api-0.0.12/lib/salesforce_bulk_api/job.rb:175:in `block in get_job_result'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `call'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
        from /u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/salesforce_bulk_api-0.0.12/lib/salesforce_bulk_api/job.rb:172:in `get_job_result'
        from /u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/salesforce_bulk_api-0.0.12/lib/salesforce_bulk_api.rb:79:in `do_operation'
        from /u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/salesforce_bulk_api-0.0.12/lib/salesforce_bulk_api.rb:29:in `update'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/sfdc.rb:49:in `do_bulk!'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/sfdc.rb:26:in `update_object!'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/sfdc.rb:18:in `update_transaction_object!'
        from /u/apps/pd_bizops_integration/releases/20150821062234/app/models/tasks/sfdc_transaction_updater.rb:49:in `update'
        from /u/apps/pd_bizops_integration/releases/20150821062234/app/models/tasks/sfdc_transaction_updater.rb:6:in `block in run'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/cron_utils.rb:26:in `call'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/cron_utils.rb:26:in `block (2 levels) in run_with_lock_and_benchmark'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/cron_utils.rb:16:in `block in filelock'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/cron_utils.rb:14:in `open'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/cron_utils.rb:14:in `filelock'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/cron_utils.rb:25:in `block in run_with_lock_and_benchmark'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
        from /u/apps/pd_bizops_integration/releases/20150821062234/lib/cron_utils.rb:24:in `run_with_lock_and_benchmark'
        from /u/apps/pd_bizops_integration/releases/20150821062234/app/models/tasks/sfdc_transaction_updater.rb:5:in `run'
        from (eval):1:in `<top (required)>'
        from /u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/railties-3.2.17/lib/rails/commands/runner.rb:54:in `eval'
        from /u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/railties-3.2.17/lib/rails/commands/runner.rb:54:in `<top (required)>'
        from /u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/railties-3.2.17/lib/rails/commands.rb:64:in `require'
        from /u/apps/pd_bizops_integration/shared/bundle/ruby/2.2.0/gems/railties-3.2.17/lib/rails/commands.rb:64:in `<top (required)>'
        from script/rails:12:in `require'
        from script/rails:12:in `<main>'
```

**Comment by polycarpou** [comment]
I am running into this issue as well. Did you find any more info about this?
